accelerator: null
accumulate_grad_batches: null
adv_temp: 1.0
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
axiom_types: 10
axiom_weight: 1.0
benchmark: false
bern_flag: false
calc_hits:
- 10
- 5
- 3
- 1
check_per_epoch: 2
check_val_every_n_epoch: 10
checkpoint_callback: null
checkpoint_dir: ''
cog_gamma: 0.5
cog_num: 0
cognitive: false
config_path: ''
confidence_filter: 0
data_class: KGDataModule
data_path: dataset/nl27k
dataset_name: nl27k
decoder_model: null
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
dis_order: 2
dropout: 0
early_stop_patience: 10
emb_dim: 128
emb_shape: 20
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
eval_bs: 8
eval_task: confidence_prediction
fast_dev_run: false
fet_drop: 0.2
filter_flag: true
flush_logs_every_n_steps: null
freq_init: 4
gpu: cuda:0
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hid_drop: 0.3
hid_size: 9728
inject_triple_percent: 1.0
inp_drop: 0.2
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: ssCDLLitModel
load_config: false
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss_name: ssCDL_loss
lr: 1.0e-03
margin: 4.0
max_entialments: 2000
max_epochs: 1200
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_name: ssCDL
monitor: MAE
move_metrics_to_cpu: false
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: false
norm_flag: false
num_batches: 0
num_ent: 4999
num_epoch: 1000
num_layers: 2
num_neg: 50
num_nodes: 1
num_processes: 1
num_rel: 7
num_sanity_val_steps: 2
num_workers: 0
opn: corr
optim_name: Adam
out_dim: 200
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
regularization: 0.0
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_config: false
seed: 321
select_probability: 0.8
shuffle: true
slackness_penalty: 0.01
smoothing: 0.1
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
test_only: false
test_sampler_class: UKGETestSampler
tpu_cores: null
track_grad_norm: -1
train_bs: 4096
train_sampler_class: UKGEUniSampler
update_axiom_per: 2
use_wandb: false
use_weight: false
val_check_interval: 1.0
weight_decay: 0.01
weights_save_path: null
weights_summary: top
sigma: 0.6
size: 101
weightloss: 0.7
thereshold: 0.03
lower_bound: 0
upper_bound: 0